---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:william302/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: william902/podinfo
      tag: dev-hdtwcel9
    replicaCount: 1
    hpa:
      enabled: false
